# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data Science with Big Dillinger
#email: frank.fineis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts about Data Science, R and Python tutorials, and life as a Statistics graduate student at Northwestern
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bigdillinger
github_username:  ffineis

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
